# Generated by Django 5.2 on 2026-07-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobid', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=15)),
                ('emailaddress', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=20)),
                ('keyskill', models.CharField(max_length=500)),
                ('applieddate', models.CharField(max_length=30)),
            ],
        ),
    ]
